second commit
Sindhujarajen/online-shopping pull request #3
Opened 2022-12-08 16:58 UTC by Sindhujarajen

2022-12-12 06:59 UTC, Sushmitha-Vk requested changes

2022-12-12 06:59 UTC, Sushmitha-Vk commented on first_project/src/app/header/header.component.html
> +                      <p> <a mat-list-item appHighlight background="orange" routerLink="/goshopping"(click)="snav.toggle()">Clothes</a></p>
there is no child routes still...?

2022-12-12 10:01 UTC, Sindhujarajen commented on first_project/src/app/header/header.component.html
> +                      <p> <a mat-list-item appHighlight background="orange" routerLink="/goshopping"(click)="snav.toggle()">Clothes</a></p>
resolved mam

2022-12-13 06:46 UTC, Sushmitha-Vk requested changes

2022-12-13 06:46 UTC, Sushmitha-Vk commented on first_project/src/app/goshopping/goshopping.component.ts
> +    // this.service.getClothes().pipe(takeUntil(this.onDestroy$)).subscribe((code: any) => {
remove commented codes

2022-12-13 06:46 UTC, Sushmitha-Vk commented on first_project/src/app/goshopping/goshopping.component.ts
> +       console.log('-----',routelink)
remove console.logs

2022-12-14 06:56 UTC, Sindhujarajen commented on first_project/src/app/goshopping/goshopping.component.ts
> +    // this.service.getClothes().pipe(takeUntil(this.onDestroy$)).subscribe((code: any) => {
resolved mam

2022-12-14 06:56 UTC, Sindhujarajen commented on first_project/src/app/goshopping/goshopping.component.ts
> +       console.log('-----',routelink)
resolved mam

2022-12-14 09:08 UTC, Sushmitha-Vk approved these changes

2022-12-14 09:09 UTC, Sushmitha-Vk commented
resolve conflicts

2022-12-14 11:24 UTC, Sushmitha-Vk approved these changes

2022-12-14 17:06 UTC, merged