interface
Sindhujarajen/online-shopping pull request #4
Opened 2022-12-13 09:43 UTC by Sindhujarajen

2022-12-13 12:55 UTC, Sushmitha-Vk requested changes

2022-12-13 12:55 UTC, Sushmitha-Vk commented on first_project/src/app/goshopping/goshopping.component.ts
> -}
comments

2022-12-13 12:55 UTC, Sushmitha-Vk commented on first_project/src/app/header/header.component.css
> -}  */
comments

2022-12-13 12:55 UTC, Sushmitha-Vk commented on first_project/src/app/login/login.component.html
> -        </div> -->
comments

2022-12-13 12:55 UTC, Sushmitha-Vk commented on first_project/src/app/mat-table/mat-table.component.ts
>    [x: string]: any;
where us x used..?

2022-12-13 12:55 UTC, Sushmitha-Vk commented on first_project/src/app/mat-table/mat-table.component.ts
> -export interface PeriodicElement {
where is PeriodicElement used..?

2022-12-14 05:12 UTC, Sushmitha-Vk approved these changes

2022-12-14 05:28 UTC, Sindhujarajen commented on first_project/src/app/mat-table/mat-table.component.ts
>    [x: string]: any;
resolved mam

2022-12-14 05:28 UTC, Sushmitha-Vk approved these changes

2022-12-14 09:08 UTC, merged